# Generated by Django 4.0.3 on 2022-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gallery_img1', models.ImageField(upload_to='')),
                ('gallery_img2', models.ImageField(upload_to='')),
                ('gallery_img3', models.ImageField(upload_to='')),
                ('gallery_img4', models.ImageField(upload_to='')),
                ('gallery_img6', models.ImageField(upload_to='')),
                ('gallery_img7', models.ImageField(upload_to='')),
                ('gallery_img8', models.ImageField(upload_to='')),
                ('gallery_img9', models.ImageField(upload_to='')),
                ('gallery_img10', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Batch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gallery_img1', models.ImageField(upload_to='')),
                ('gallery_img2', models.ImageField(upload_to='')),
                ('gallery_img3', models.ImageField(upload_to='')),
                ('gallery_img4', models.ImageField(upload_to='')),
                ('gallery_img6', models.ImageField(upload_to='')),
                ('gallery_img7', models.ImageField(upload_to='')),
                ('gallery_img8', models.ImageField(upload_to='')),
                ('gallery_img9', models.ImageField(upload_to='')),
                ('gallery_img10', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Batch3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gallery_img1', models.ImageField(upload_to='')),
                ('gallery_img2', models.ImageField(upload_to='')),
                ('gallery_img3', models.ImageField(upload_to='')),
                ('gallery_img4', models.ImageField(upload_to='')),
                ('gallery_img6', models.ImageField(upload_to='')),
                ('gallery_img7', models.ImageField(upload_to='')),
                ('gallery_img8', models.ImageField(upload_to='')),
                ('gallery_img9', models.ImageField(upload_to='')),
                ('gallery_img10', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Batch4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gallery_img1', models.ImageField(upload_to='')),
                ('gallery_img2', models.ImageField(upload_to='')),
                ('gallery_img3', models.ImageField(upload_to='')),
                ('gallery_img4', models.ImageField(upload_to='')),
                ('gallery_img6', models.ImageField(upload_to='')),
                ('gallery_img7', models.ImageField(upload_to='')),
                ('gallery_img8', models.ImageField(upload_to='')),
                ('gallery_img9', models.ImageField(upload_to='')),
                ('gallery_img10', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Batch5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gallery_img1', models.ImageField(upload_to='')),
                ('gallery_img2', models.ImageField(upload_to='')),
                ('gallery_img3', models.ImageField(upload_to='')),
                ('gallery_img4', models.ImageField(upload_to='')),
                ('gallery_img6', models.ImageField(upload_to='')),
                ('gallery_img7', models.ImageField(upload_to='')),
                ('gallery_img8', models.ImageField(upload_to='')),
                ('gallery_img9', models.ImageField(upload_to='')),
                ('gallery_img10', models.ImageField(upload_to='')),
                ('gallery_img11', models.ImageField(upload_to='')),
            ],
        ),
    ]
