# Generated by Django 4.0.3 on 2022-04-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch1',
            options={'verbose_name_plural': 'Batch1'},
        ),
        migrations.AlterModelOptions(
            name='batch2',
            options={'verbose_name_plural': 'Batch2'},
        ),
        migrations.AlterModelOptions(
            name='batch3',
            options={'verbose_name_plural': 'Batch3'},
        ),
        migrations.AlterModelOptions(
            name='batch4',
            options={'verbose_name_plural': 'Batch1'},
        ),
        migrations.AlterModelOptions(
            name='batch5',
            options={'verbose_name_plural': 'Batch1'},
        ),
    ]
